// Industries and job categories for Creerlio Platform
// Auto-generated from MASTER_DATA_SPECIFICATION.md

export const INDUSTRIES = [
  'Accounting',
  'Administration & Office Support',
  'Advertising, Arts & Media',
  'Banking & Financial Services',
  'Call Centre & Customer Service',
  'CEO & General Management',
  'Community Services & Development',
  'Construction',
  'Consulting & Strategy',
  'Design & Architecture',
  'Education & Training',
  'Engineering',
  'Farming, Animals & Conservation',
  'Government & Defence',
  'Healthcare & Medical',
  'Hospitality & Tourism',
  'Human Resources & Recruitment',
  'Information & Communication Technology (ICT)',
  'Insurance & Superannuation',
  'Legal',
  'Manufacturing, Transport & Logistics',
  'Marketing & Communications',
  'Mining, Resources & Energy',
  'Real Estate & Property',
  'Retail & Consumer Products',
  'Sales',
  'Science & Technology',
  'Sport & Recreation',
  'Trades & Services',
  'Voluntary, Charity & Not-for-Profit',
  'Indigenous & Multicultural Affairs',
  'Self Employment',
  'Other',
] as const;

export type Industry = typeof INDUSTRIES[number];

export const JOB_SUB_CATEGORIES = {
  'Accounting': [
    'Accounts Officers/Clerks',
    'Accounts Payable',
    'Accounts Receivable',
    'Audit - Internal',
    'Audit - External',
    'Bookkeeping & Small Practice Accounting',
    'Business Services & Corporate Advisory',
    'Company Secretaries',
    'Financial Accounting & Reporting',
    'Financial Managers & Controllers',
    'Forensic Accounting & Investigation',
    'Insolvency & Corporate Recovery',
    'Management Accounting & Budgeting',
    'Payroll',
    'Risk & Compliance',
    'Taxation',
  ],
  'Administration & Office Support': [
    'Administrative Assistants',
    'Call Centre - Inbound Operations',
    'Call Centre - Outbound Operations',
    'Call Centre - Management',
    'Call Centre - Other',
    'Charity, Volunteer & Not For Profit Work',
    'Clergy & Religious',
    'Community Development Workers',
    'Counsellors',
    'Data Entry & Word Processing',
    'Executive Assistants',
    'Office Management',
    'Personal Assistants',
    'Receptionists',
    'Secretarial',
    'Records Management & Document Control',
    'Switchboard/Reception',
  ],
  'Hospitality & Tourism': [
    'Bar & Beverage Staff',
    'Chefs/Cooks',
    'Front Office & Guest Services',
    'Gaming',
    'Housekeeping',
    'Kitchen & Sandwich Hands',
    'Management - Clubs & Pubs',
    'Management - Hotels & Resorts',
    'Management - QSR & Fast Food Chains',
    'Management - Restaurants & Catering',
    'Management - Travel & Tourism',
    'Reservations',
    'Room Attendants & Housekeepers',
    'Tour Guides',
    'Wait Staff',
    'Event Management',
  ],
  'Construction': [
    'Bricklaying',
    'Building Certifiers/Inspectors',
    'Concreting',
    'Estimating',
    'Facade Installation',
    'Foremen/Supervisors',
    'Labourers',
    'Landscaping & Gardening',
    'Painting & Decorating',
    'Plant & Machinery Operators',
    'Plumbing',
    'Project Management - Construction',
    'Quantity Surveying',
    'Roofing',
    'Scaffolding',
    'Site Management',
    'Surveying',
    'Tiling',
    'White Card Holders',
    'WHS / OHS',
  ],
  'Healthcare & Medical': [
    'Aged & Disability Support',
    'Allied Health',
    'Ambulance/Paramedics',
    'Chiropractic & Osteopathic',
    'Dental - Dentists',
    'Dental - Hygienists & Therapists',
    'Dental - Technicians & Assistants',
    'General Practitioners',
    'Medical Administration',
    'Medical Imaging - Radiography & Sonography',
    'Medical Specialists',
    'Mental Health & Counselling',
    'Nursing - Enrolled/Division 2',
    'Nursing - Registered',
    'Nursing - Nurse Practitioners',
    'Occupational Therapy',
    'Optometry',
    'Pathology & Diagnostic Medicine',
    'Pharmacy',
    'Physiotherapy',
    'Psychology & Counselling',
    'Speech Pathology',
  ],
  'Information & Communication Technology (ICT)': [
    'Architects',
    'Business/Systems Analysts',
    'Computer Operators',
    'Consultants',
    'Database Development & Administration',
    'Developers/Programmers',
    'Engineering - Hardware',
    'Engineering - Network',
    'Engineering - Software',
    'Help Desk & IT Support',
    'Management',
    'Networks & Systems Administration',
    'Product Management & Development',
    'Project Management',
    'Sales - Pre & Post',
    'Security',
    'Systems Architects',
    'Testing & Quality Assurance',
    'Telecommunications',
    'Web Development & Production',
    'DevOps',
    'Cloud Architecture',
    'Cybersecurity',
    'Data Science & Analytics',
    'Machine Learning & AI',
  ],
  'Trades & Services': [
    'Air Conditioning & Refrigeration',
    'Automotive Trades',
    'Building Trades',
    'Cabinet Making',
    'Carpentry',
    'Electrical',
    'Electronics & Communications',
    'Fitters, Turners & Machinists',
    'Floristry',
    'Gardening & Landscaping',
    'Hair & Beauty Services',
    'Locksmiths',
    'Mechanics - Motor Vehicle',
    'Panel Beating & Spray Painting',
    'Plumbing',
    'Printing & Publishing',
    'Signage & Graphics',
    'Telecommunications Trades',
    'Toolmaking',
    'Upholstery',
    'Welding & Fabrication',
  ],
  'Manufacturing, Transport & Logistics': [
    'Air Transport & Aviation',
    'Analysis & Reporting',
    'Courier/Postal Services',
    'Dispatch & Scheduling',
    'Distribution Management',
    'Fleet Management',
    'Forklift Operators',
    'Import/Export & Customs',
    'Inventory Management/Stock Control',
    'Logistics Management',
    'Marine & Maritime',
    'Pickers & Packers',
    'Rail & Bus',
    'Road Transport',
    'Store Persons',
    'Supply Chain Management',
    'Train Drivers',
    'Truck Drivers - Heavy Rigid (HR)',
    'Truck Drivers - Heavy Combination (HC)',
    'Truck Drivers - Multi Combination (MC)',
    'Truck Drivers - Medium Rigid (MR)',
    'Truck Drivers - Light Rigid (LR)',
    'Warehouse Management',
  ],
  'Mining, Resources & Energy': [
    'Analysis & Reporting',
    'Drilling',
    'Engineering & Maintenance',
    'Environmental, Health & Safety',
    'Exploration & Geoscience',
    'Management',
    'Mine Management',
    'Oil & Gas Drilling & Exploration',
    'Oil & Gas Production',
    'Refining',
    'Processing',
    'Production & Operations',
    'Project Management',
    'Shutdown & Turnaround',
    'Surveying',
    'Training & Development',
    'Underground Mining',
    'Open Cut Mining',
  ],
  'Engineering': [
    'Aerospace Engineering',
    'Automotive Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil/Structural Engineering',
    'Drafting & Design',
    'Electrical/Electronic Engineering',
    'Environmental Engineering',
    'Field Engineering',
    'Industrial Engineering',
    'Maintenance',
    'Mechanical Engineering',
    'Mining Engineering',
    'Oil & Gas Engineering',
    'Planning & Scheduling',
    'Power & Energy',
    'Process Engineering',
    'Production & Manufacturing',
    'Project Engineering',
    'Quality Assurance & Control',
    'Rail Engineering',
    'Site Engineering',
    'Structural Engineering',
    'Systems Engineering',
    'Water & Waste Engineering',
  ],
} as const;

export type JobSubCategory = typeof JOB_SUB_CATEGORIES[keyof typeof JOB_SUB_CATEGORIES][number];

export const EMPLOYMENT_TYPES = [
  'Full-time',
  'Part-time',
  'Casual',
  'Contract/Temp',
  'Apprenticeship',
  'Traineeship',
  'Internship',
  'Graduate Program',
  'Work Experience',
  'Volunteer',
  'Seasonal',
  'Shift Work',
  'Fixed Term Contract',
  'Permanent',
  'Labour Hire',
] as const;

export type EmploymentType = typeof EMPLOYMENT_TYPES[number];

// Helper functions
export const getSubCategoriesForIndustry = (industry: Industry): readonly string[] => {
  return JOB_SUB_CATEGORIES[industry] || [];
};

export const searchIndustries = (query: string, limit: number = 20): readonly Industry[] => {
  const lowerQuery = query.toLowerCase();
  return INDUSTRIES
    .filter(ind => ind.toLowerCase().includes(lowerQuery))
    .slice(0, limit);
};

export const searchSubCategories = (
  industry: Industry,
  query: string,
  limit: number = 20
): readonly string[] => {
  const subCats = getSubCategoriesForIndustry(industry);
  const lowerQuery = query.toLowerCase();
  return subCats
    .filter(sub => sub.toLowerCase().includes(lowerQuery))
    .slice(0, limit);
};
