export const INDUSTRY_OPTIONS = [
  'Agriculture, Food & Natural Resources',
  'Agriculture & Farming',
  'Food & Beverage Manufacturing',
  'Fisheries & Aquaculture',
  'Forestry & Timber',
  'Horticulture & Viticulture',
  'Mining & Resources',
  'Energy & Utilities',
  'Manufacturing, Engineering & Construction',
  'Manufacturing',
  'Advanced Manufacturing',
  'Construction & Building',
  'Civil & Infrastructure',
  'Engineering Services',
  'Industrial Design',
  'Trades & Skilled Labour',
  'Technology & Digital',
  'Information Technology (IT)',
  'Software & SaaS',
  'Data, AI & Analytics',
  'Cybersecurity',
  'Telecommunications',
  'Hardware & Electronics',
  'Digital Platforms & Marketplaces',
  'Professional & Business Services',
  'Accounting & Finance',
  'Legal Services',
  'Consulting & Advisory',
  'Human Resources & Recruitment',
  'Marketing & Advertising',
  'Public Relations & Communications',
  'Business Services',
  'Healthcare, Medical & Community',
  'Healthcare & Medical',
  'Hospitals & Clinics',
  'Allied Health',
  'Mental Health Services',
  'Aged Care & Disability Services',
  'Community & Social Services',
  'Pharmaceutical & Biotech',
  'Education, Training & Research',
  'Early Childhood Education',
  'Primary & Secondary Education',
  'Tertiary Education',
  'Vocational Training & RTOs',
  'Corporate Training',
  'Research & Development',
  'Retail, Wholesale & Consumer',
  'Retail',
  'E-commerce',
  'Wholesale & Distribution',
  'FMCG',
  'Consumer Goods',
  'Luxury & Premium Goods',
  'Hospitality, Tourism & Leisure',
  'Hospitality',
  'Food Services',
  'Accommodation & Hotels',
  'Tourism & Travel',
  'Events & Entertainment',
  'Sport & Recreation',
  'Transport, Logistics & Supply Chain',
  'Transport & Logistics',
  'Freight & Shipping',
  'Warehousing & Distribution',
  'Aviation',
  'Automotive & Mobility',
  'Supply Chain Management',
  'Property, Infrastructure & Facilities',
  'Real Estate',
  'Property Development',
  'Facilities Management',
  'Commercial Property',
  'Residential Property',
  'Urban Planning',
  'Creative, Media & Design',
  'Creative Services',
  'Media & Publishing',
  'Film, TV & Radio',
  'Design & UX',
  'Architecture',
  'Arts & Culture',
  'Government, Defence & Public Sector',
  'Government',
  'Local Government',
  'Defence & Aerospace',
  'Public Administration',
  'Emergency & Protective Services',
  'Environmental & Sustainability',
  'Environmental Services',
  'Sustainability & ESG',
  'Renewable Energy',
  'Waste & Recycling',
  'Climate & Conservation',
  'Other / Emerging Industries',
  'Startups & Scaleups',
  'Social Enterprise',
  'Non-Profit & Charity',
  'Religious & Community Organisations',
  'Other / Not Listed',
] as const

export type IndustryOption = typeof INDUSTRY_OPTIONS[number]

export const INDUSTRY_SET = new Set<string>(INDUSTRY_OPTIONS)

export const isValidIndustry = (value: string | null | undefined) => {
  if (!value) return false
  return INDUSTRY_SET.has(value)
}
