// Autocomplete data for various fields
// In production, these would come from API endpoints

export const JOB_TITLES = [
  'Senior Software Engineer',
  'Software Engineer',
  'Junior Software Engineer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'Data Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'Product Manager',
  'Technical Product Manager',
  'Project Manager',
  'Scrum Master',
  'Agile Coach',
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'Graphic Designer',
  'Business Analyst',
  'Systems Analyst',
  'QA Engineer',
  'Test Automation Engineer',
  'Security Engineer',
  'Cloud Architect',
  'Solutions Architect',
  'Technical Lead',
  'Engineering Manager',
  'Head of Engineering',
  'CTO',
  'VP Engineering'
];

export const AUSTRALIAN_CITIES = [
  { value: 'Sydney, NSW', label: 'Sydney', state: 'NSW' },
  { value: 'Melbourne, VIC', label: 'Melbourne', state: 'VIC' },
  { value: 'Brisbane, QLD', label: 'Brisbane', state: 'QLD' },
  { value: 'Perth, WA', label: 'Perth', state: 'WA' },
  { value: 'Adelaide, SA', label: 'Adelaide', state: 'SA' },
  { value: 'Canberra, ACT', label: 'Canberra', state: 'ACT' },
  { value: 'Hobart, TAS', label: 'Hobart', state: 'TAS' },
  { value: 'Darwin, NT', label: 'Darwin', state: 'NT' },
  { value: 'Gold Coast, QLD', label: 'Gold Coast', state: 'QLD' },
  { value: 'Newcastle, NSW', label: 'Newcastle', state: 'NSW' },
  { value: 'Wollongong, NSW', label: 'Wollongong', state: 'NSW' },
  { value: 'Geelong, VIC', label: 'Geelong', state: 'VIC' },
  { value: 'Townsville, QLD', label: 'Townsville', state: 'QLD' },
  { value: 'Cairns, QLD', label: 'Cairns', state: 'QLD' },
  { value: 'Toowoomba, QLD', label: 'Toowoomba', state: 'QLD' },
  { value: 'Ballarat, VIC', label: 'Ballarat', state: 'VIC' },
  { value: 'Bendigo, VIC', label: 'Bendigo', state: 'VIC' },
  { value: 'Albury, NSW', label: 'Albury', state: 'NSW' },
  { value: 'Launceston, TAS', label: 'Launceston', state: 'TAS' },
  { value: 'Mackay, QLD', label: 'Mackay', state: 'QLD' }
];

export const AUSTRALIAN_STATES = [
  'NSW - New South Wales',
  'VIC - Victoria',
  'QLD - Queensland',
  'WA - Western Australia',
  'SA - South Australia',
  'TAS - Tasmania',
  'ACT - Australian Capital Territory',
  'NT - Northern Territory'
];

export const INDUSTRIES = [
  'Information Technology',
  'Software Development',
  'Financial Services',
  'Banking',
  'Healthcare',
  'Education',
  'Retail',
  'E-commerce',
  'Manufacturing',
  'Construction',
  'Real Estate',
  'Telecommunications',
  'Media & Entertainment',
  'Marketing & Advertising',
  'Professional Services',
  'Legal',
  'Accounting',
  'Consulting',
  'Hospitality',
  'Tourism',
  'Transport & Logistics',
  'Energy & Utilities',
  'Mining',
  'Agriculture',
  'Government',
  'Non-Profit',
  'Pharmaceuticals',
  'Biotechnology',
  'Insurance',
  'Aviation'
];

export const SKILLS = [
  'React',
  'Angular',
  'Vue.js',
  'Next.js',
  'Node.js',
  'Python',
  'Java',
  'C#',
  '.NET',
  'TypeScript',
  'JavaScript',
  'HTML',
  'CSS',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'Git',
  'Agile',
  'Scrum',
  'REST APIs',
  'GraphQL',
  'Microservices',
  'CI/CD',
  'TDD',
  'Leadership',
  'Communication',
  'Problem Solving',
  'Project Management',
  'Team Collaboration',
  'Time Management',
  'Critical Thinking'
];

export const CERTIFICATIONS = [
  { value: 'AWS Certified Solutions Architect', issuer: 'Amazon Web Services' },
  { value: 'AWS Certified Developer', issuer: 'Amazon Web Services' },
  { value: 'Microsoft Certified: Azure Administrator', issuer: 'Microsoft' },
  { value: 'Microsoft Certified: Azure Developer', issuer: 'Microsoft' },
  { value: 'Google Cloud Professional Cloud Architect', issuer: 'Google Cloud' },
  { value: 'PMP - Project Management Professional', issuer: 'PMI' },
  { value: 'Certified ScrumMaster (CSM)', issuer: 'Scrum Alliance' },
  { value: 'Certified Kubernetes Administrator', issuer: 'CNCF' },
  { value: 'CompTIA Security+', issuer: 'CompTIA' },
  { value: 'CISSP', issuer: 'ISC²' },
  { value: 'CPA - Certified Public Accountant', issuer: 'CPA Australia' },
  { value: 'CA - Chartered Accountant', issuer: 'Chartered Accountants ANZ' },
  { value: 'Six Sigma Green Belt', issuer: 'ASQ' },
  { value: 'Six Sigma Black Belt', issuer: 'ASQ' },
  { value: 'ITIL Foundation', issuer: 'Axelos' }
];

export const COMPANIES = [
  'Atlassian',
  'Canva',
  'Afterpay',
  'REA Group',
  'SEEK',
  'Telstra',
  'Commonwealth Bank',
  'Westpac',
  'ANZ',
  'NAB',
  'Woolworths Group',
  'Coles Group',
  'Wesfarmers',
  'BHP',
  'Rio Tinto',
  'Qantas',
  'Virgin Australia',
  'Optus',
  'TPG Telecom',
  'Xero',
  'WiseTech Global',
  'Aristocrat Leisure',
  'Flight Centre',
  'Cochlear',
  'CSL'
];

export const UNIVERSITIES = [
  'University of Sydney',
  'University of Melbourne',
  'Australian National University',
  'University of Queensland',
  'University of New South Wales',
  'Monash University',
  'University of Western Australia',
  'University of Adelaide',
  'University of Technology Sydney',
  'RMIT University',
  'Queensland University of Technology',
  'Curtin University',
  'Macquarie University',
  'University of Wollongong',
  'Deakin University',
  'Griffith University',
  'La Trobe University',
  'University of Newcastle',
  'University of Tasmania',
  'Swinburne University'
];

export const DEGREES = [
  'Bachelor of Science (Computer Science)',
  'Bachelor of Engineering (Software)',
  'Bachelor of Information Technology',
  'Bachelor of Business',
  'Bachelor of Commerce',
  'Bachelor of Arts',
  'Master of Science',
  'Master of Engineering',
  'Master of Business Administration (MBA)',
  'Master of Information Technology',
  'Master of Data Science',
  'PhD in Computer Science',
  'Graduate Diploma',
  'Associate Degree',
  'Certificate IV',
  'Diploma'
];

export const EMPLOYMENT_TYPES = [
  'Full-time',
  'Part-time',
  'Contract',
  'Casual',
  'Internship',
  'Apprenticeship',
  'Fixed Term'
];

export const WORK_MODELS = [
  'Remote',
  'Hybrid',
  'On-site',
  'Flexible'
];
